### PR TITLE
Visualize tracked cells and their features

### PR DESCRIPTION
**Pull request by ziw-liu**
Visualize TCZYX images and TYX tracking labels.

Loads T(N*Z) UMAP embeddings into the labels layer's attribute to be used with napari-clusters-plotter.

Hover on input fields to view tips.

## Before testing

Install again with `pip install -e ".[dev]"`.

Apple silicon users must install `higra` from conda-forge _before_ installing this plugin. Upstream issue: https://github.com/higra/Higra/issues/249

### CODE REVIEW

**Comment by mattersoflight** [comment]
@ziw-liu can you point me to paths of matching zarr stores so I can try this out?

**Comment by mattersoflight** [comment]
@ziw-liu installing `napari-clusters-plotter` via mamba as per the README of project breaks the napari environment. `pip install napari-clusters-plotter` plays well with our other instructions on Wiki.

**Comment by mattersoflight** [comment]
The loading crashed while trying the FOV `B/4/0` and is quite slow with `B/4/2` on the `login-02` node. Slowest parts are loading the movie and, somewhat surprisingly, loading features.

**Comment by mattersoflight** [comment]
@ziw-liu I now see a peculiar behavior. The INFO logs say that the data is being loaded, but the canvas stays empty. Let's take a look at this in person.

**Comment by ziw-liu** [comment]
@mattersoflight a know issue is that napari-clusters-plotter does not work with the new napari 0.5.0: https://github.com/BiAPoL/napari-clusters-plotter/pull/308#issuecomment-2243372356. However 0.5.0 brings useful features for users of other widgets so I didn't pin the version. I'm also seeing flakiness on HPC with the also newly released PyQt 6.7.0, sometimes using PyQt5 seems better.

**Comment by ziw-liu** [comment]
@mattersoflight Now if you do:

```sh
pip install -e ".[dev]"
```

This will include `[all]` that installs napari, pyqt5, and napari-clusters-plotter.

**Comment by mattersoflight** [comment]
@ziw-liu works well. I enjoyed watching cells move from one part of UMAP space to another. The viewer widget can use a few tweaks (after the current work on data formats and VisCy is completed):
- show tracks (via `napari.view_tracks()`.
- rename the fields for clarity.

**Comment by Soorya19Pradeep** [comment]
@ziw-liu, I was able to use the plugin as well. I can see the whole track of the cell starting from timepoint 0. Is it possible to visualize the progression of tracking along time instead?
image

**Comment by ziw-liu** [comment]
@Soorya19Pradeep trajectory dimensionality has been fixed.

**Comment by mattersoflight** [comment]
@ziw-liu the dependencies for the plugin need to be worked out and documented. 

I needed to install the following:
* iohub from github (`main` branch)
* ultrack

Since this plugin is experimental, why not install iohub from github? 
Although `napari-clusters-plotter` requires numpy ~<1.26, it worked just fine with numpy 2.0.2 installed by ultrack.

Also could you do the following to improve the analysis workflow?
* compute the 3-component UMAP and 6-component PCA  across all FOVs in advance to enable comparison of cells across FOVs.
* our widget is renamed `track embeddings`.
* our widget loads the `napari-clusters-plotter/plotter-widget`.

**Comment by mattersoflight** [comment]
Animations like the following are very useful to explore each FOV. The speed of analysis will improve if we don't have to call the dimensionality reduction for each FOV.
https://github.com/user-attachments/assets/97fc8824-622b-44ff-b324-212932fc08b3

**Comment by mattersoflight** [comment]
I wasn't able to color the instances manually - perhaps because I have napari 0.5. I get following error when I draw a ROI.
```
File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari_clusters_plotter/_Qt_code.py", line 516, in onselect
    self.parent.manual_clustering_method(self.ind_mask)
  File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari_clusters_plotter/_plotter.py", line 125, in manual_clustering_method
    self.run(
  File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari_clusters_plotter/_plotter.py", line 730, in run
    self._update_cluster_image(
  File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari_clusters_plotter/_plotter.py", line 805, in _update_cluster_image
    self.visualized_layer = self._draw_cluster_image(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari_clusters_plotter/_plotter.py", line 862, in _draw_cluster_image
    cluster_layer = Layer.create(
                    ^^^^^^^^^^^^^
  File "/hpc/mydata/shalin.mehta/envs/ndutils/lib/python3.11/site-packages/napari/layers/base/base.py", line 2310, in create
    raise TypeError(
TypeError: _add_layer_from_data received an unexpected keyword argument ('color') for layer type labels
```

**Comment by ziw-liu** [comment]
> dependencies for the plugin need to be worked out and documented.

@mattersoflight I fixed it in https://github.com/czbiohub-sf/napari-iohub/pull/13/commits/6d1b8f4a014a660f4f9acb7caee2badfd0b5494a. Did you run installation again after pulling?

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , I am getting the following error after I pulled the changes:

> File /hpc/mydata/soorya.pradeep/tracking/lib/python3.10/site-packages/npe2/_command_registry.py:34, in CommandHandler.resolve(self=CommandHandler(id='napari-iohub.get_reader', fun...on_name='napari_iohub._reader:napari_get_reader'))
>      32     self.function = utils.import_python_name(self.python_name)
>      33 except Exception as e:
> ---> 34     raise RuntimeError(
>         self.python_name = 'napari_iohub._reader:napari_get_reader'
>         self = CommandHandler(id='napari-iohub.get_reader', function=None, python_name='napari_iohub._reader:napari_get_reader')
>      35         f"Failed to import command at {self.python_name!r}: {e}"
>      36     ) from e
>      38 return self.function
> 
> RuntimeError: Failed to import command at 'napari_iohub._reader:napari_get_reader': No module named 'iohub.ngff.nodes'; 'iohub.ngff' is not a package

Any idea what happened here?

**Comment by Soorya19Pradeep** [comment]
Thanks @ziw-liu ! It works well!

**Review by Soorya19Pradeep — APPROVED** [review]
I have tested visualizing tracks and features for the June dataset using these changes. Works really well!

**Pull request merged**
